#server.port=8090

server:
  port: 8090

#spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html


# log info
logging:
  level:
    root: info
    itcen:
      backapi: debug
    org:
      hibernate: info



# DB 정보
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/restdb
    username: root
    password: mariadb

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB106Dialect #방언 설정 //
    show-sql: true # SQL 문 로그
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true



# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /myapi.html





# template
#spring:
#  mvc:
#    view:
#      suffix: .html


#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=


